// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const PUBLIC_SUPABASE_ENV_NAMES = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_PUBLISHABLE_KEY',
] as const;

function getServerEnv(name: string) {
  return typeof process !== 'undefined' ? process.env[name] : undefined;
}

function cleanEnvValue(value: string | undefined) {
  const trimmed = value?.trim();
  if (!trimmed) return undefined;

  const quote = trimmed[0];
  if ((quote === '"' || quote === "'") && trimmed.endsWith(quote)) {
    return trimmed.slice(1, -1).trim();
  }

  return trimmed;
}

function createDisabledSupabaseClient(message: string) {
  const result = Promise.resolve({ data: null, error: new Error(message) });

  const query = new Proxy(
    {},
    {
      get() {
        return () => query;
      },
    },
  ) as any;

  query.then = result.then.bind(result);
  query.catch = result.catch.bind(result);
  query.finally = result.finally.bind(result);

  return new Proxy(
    {},
    {
      get(_, prop) {
        if (prop === 'auth') {
          return {
            getSession: async () => ({ data: { session: null }, error: new Error(message) }),
            onAuthStateChange: () => ({
              data: { subscription: { unsubscribe: () => undefined } },
            }),
          };
        }

        if (prop === 'from' || prop === 'rpc' || prop === 'storage') {
          return () => query;
        }

        return undefined;
      },
    },
  ) as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for the browser bundle. Fall back to process.env only
  // during SSR, where Vercel runtime variables are available per request.
  const SUPABASE_URL = cleanEnvValue(
    import.meta.env.VITE_SUPABASE_URL ||
    getServerEnv('VITE_SUPABASE_URL') ||
    getServerEnv('SUPABASE_URL'),
  );
  const SUPABASE_PUBLISHABLE_KEY = cleanEnvValue(
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    getServerEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ||
    getServerEnv('SUPABASE_PUBLISHABLE_KEY'),
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL or SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY or SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Add ${PUBLIC_SUPABASE_ENV_NAMES.join(', ')} to Vercel for the client build and runtime.`;
    console.error('[Supabase] Client config error', {
      missing,
      hasViteUrl: Boolean(import.meta.env.VITE_SUPABASE_URL),
      hasVitePublishableKey: Boolean(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY),
      hasRuntimeUrl: Boolean(getServerEnv('VITE_SUPABASE_URL') || getServerEnv('SUPABASE_URL')),
      hasRuntimePublishableKey: Boolean(
        getServerEnv('VITE_SUPABASE_PUBLISHABLE_KEY') || getServerEnv('SUPABASE_PUBLISHABLE_KEY'),
      ),
    });
    return createDisabledSupabaseClient(message);
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (error) {
    console.error('[Supabase] Client initialization failed', error);
    const message = error instanceof Error ? error.message : 'Supabase client initialization failed.';
    return createDisabledSupabaseClient(message);
  }
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

